task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

to_do/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from task.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls', namespace='todos')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

task/forms.py
from django.forms import ModelForm
from .models import Task
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'is_completed']


User = get_user_model()


class CreateUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', ]
        field_classes = {'username': UsernameField}

task/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from .models import Task
from .forms import TaskForm, CreateUserCreationForm
from django.core.mail import send_mail
from django.views import generic
from django.contrib.auth.decorators import login_required


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CreateUserCreationForm

    def get_success_url(self):
        return reverse("login")


def list(request):
    tasks = Task.objects.all()
    context = {
        'tasks': tasks
    }
    return render(request, 'list.html', context)


@login_required
def detail(request, pk):
    task = Task.objects.get(id=pk)
    context = {
        'task': task
    }
    return render(request, 'detail.html', context)


def create(request):
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            send_mail(
                subject="A task has been created",
                message="Go to the list to see it",
                from_email="test@test.com",
                recipient_list=["test2@test.com"]
            )
            return redirect(reverse('todos:list'))

    context = {
        'form': form
    }
    return render(request, 'create.html', context)


def update(request, pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect(reverse('todos:list'))

    context = {
        'form': form
    }
    return render(request, 'update.html', context)


def delete(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    return redirect(reverse('todos:list'))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todos</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
<body>
<nav>
    <a href="{% url 'todos:list' %}">Todos</a>
    {% if user.is_authenticated %}
    logged in as: {{request.user.username}}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'signup' %}">SignUp</a>

    {% endif %}
</nav>
{% block content %}
{% endblock %}
<hr>
<a href="{% url 'todos:create' %}">Create</a>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/create.html
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block content %}
    {{task.description}}
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block content %}
<form>
    <div id="todo-list">
        {% for item in tasks %}
            <p>
                <input type="checkbox" id="item{{ item.id }}" onclick="toggleCompletion({{item.id}})">
                <label for="item{{ item.id }}" ><a href="{% url 'todos:detail' item.id %}">{{ item.title }}</a></label>
                <a href="{% url 'todos:update' item.id %}">Edit</a>
                <a href="{% url 'todos:delete' item.id %}">Delete</a>
            </p>
        {% endfor %}
    </div>
</form>
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
{% endblock %}